
export const CREDITS_IMG_BASE = "/images/credits";
export const PLACEHOLDER = `${CREDITS_IMG_BASE}/placeholder.png`;

export const teams = [
  {
    title: "Lead",
    members: [
      {
        name: "Arjun Nair",
        role: "Overall Coordinator",
        message: "Steering the ship through uncharted waters 🚀",
        image: "/images/credits/arjun.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Priya Sharma",
        role: "Technical Head",
        message: "Turning chaos into clean architecture ✨",
        image: "/images/credits/priya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Rahul Menon",
        role: "Convener",
        message: "Dream big, execute relentlessly 🔥",
        image: "/images/credits/rahul.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Ananya Iyer",
        role: "Management Lead",
        message: "Building things people truly love to use 💡",
        image: "/images/credits/ananya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Karthik Pillai",
        role: "Operations Lead",
        message: "Keeping the momentum alive 24/7 ⚡",
        image: "/images/credits/karthik.jpg",
        linkedin: "#",
        github: "#",
      },
    ],
  },
  {
    title: "Frontend",
    members: [
      {
        name: "Diya Patel",
        role: "Frontend Lead",
        message: "Obsessed with 60fps animations & micro-interactions 🎨",
        image: "/images/credits/diya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Rohan Krishnan",
        role: "UI Engineer",
        message: "Centering divs and crafting sleek layouts since day one 💻",
        image: "/images/credits/rohan.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Sneha Reddy",
        role: "Frontend Dev",
        message: "Pixels with purpose, code with heart ❤️",
        image: "/images/credits/sneha.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Aditya Verma",
        role: "Creative Dev",
        message: "Crafting visual symphonies across the web 🌌",
        image: "/images/credits/aditya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Meera Joshi",
        role: "Frontend Dev",
        message: "Coffee in, responsive UI components out ☕",
        image: "/images/credits/meera.jpg",
        linkedin: "#",
        github: "#",
      },
    ],
  },
  {
    title: "Backend",
    members: [
      {
        name: "Vikram Singh",
        role: "Backend Lead",
        message: "Low latency, high concurrency, zero downtime 🛡️",
        image: "/images/credits/vikram.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Ishita Das",
        role: "Systems Engineer",
        message: "Scaling databases and pipelines to the moon 🌙",
        image: "/images/credits/ishita.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Nikhil Rao",
        role: "API Architect",
        message: "Clean endpoints and bulletproof queries ⚡",
        image: "/images/credits/nikhil.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Tara Nambiar",
        role: "Cloud & DevOps",
        message: "Automating deployments and cloud resilience 🤖",
        image: "/images/credits/tara.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Siddharth Menon",
        role: "Backend Dev",
        message: "If it works in production, celebrate quietly 🕶️",
        image: "/images/credits/siddharth.jpg",
        linkedin: "#",
        github: "#",
      },
    ],
  },
  {
    title: "UI / UX",
    members: [
      {
        name: "Kavya Nair",
        role: "Design Lead",
        message: "Designing intuitive futures, one frame at a time ✒️",
        image: "/images/credits/kavya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Arjun Das",
        role: "Product Designer",
        message: "Form follows function, always 📐",
        image: "/images/credits/arjundas.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Riya Kapoor",
        role: "Visual Designer",
        message: "Color palettes and aesthetics that spark joy 🌈",
        image: "/images/credits/riya.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Dev Shah",
        role: "Motion Designer",
        message: "Breathing dynamic life into static concepts ✨",
        image: "/images/credits/dev.jpg",
        linkedin: "#",
        github: "#",
      },
      {
        name: "Maya Iyer",
        role: "UX Researcher",
        message: "Empathy-driven experiences designed for humans 🧠",
        image: "/images/credits/maya.jpg",
        linkedin: "#",
        github: "#",
      },
    ],
  },
];
